run:
  timeout: 10m

linters-settings:
  gofumpt:
    extra-rules: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/werf/)
  gocritic:
    disabled-checks:
      - ifElseChain
  errorlint:
    comparison: false
    asserts: false
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - ineffassign
    - typecheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - errname
    - errorlint
    - exportloopref
    - gci
    - gocritic
    - gofumpt
    - misspell
    - nolintlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - playground
    - docs
    - scripts
    - stapel
  exclude:
    - "non-wrapping format verb for fmt.Errorf" # errorlint