name: Lint

on:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install prettier
        run: task -p deps:install:prettier

      - name: Lint
        run: task -p lint:prettier
