name: Lint

on:
  workflow_call:
    inputs:
      force-skip:
        default: "false"
        type: string
      taskfile-dir:
        description: "directory where taskfile is located"
        type: string
        default: ${{ github.workspace }}
      go-version-file-dir:
        description: "directory where go.mod is located. Can be multiple dirs"
        type: string
        default: '["."]'
      packages:
        description: "packages to install"
        type: string

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install prettier
        run: task -p deps:install:prettier

      - name: Lint
        run: task -p lint:prettier

  golangci-lint:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(inputs.go-version-file-dir) }}
    steps:
      - name: Install build dependencies
        if: inputs.packages && inputs.packages != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.packages }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.directory }}/go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install golangci-lint
        run: task -p deps:install:golangci-lint

      - name: Lint
        working-directory: ${{ matrix.directory }}
        run: task -p lint:golangci-lint
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
