name: Lint

on:
  workflow_call:
    inputs:
      path-to-go-mod:
        type: string
        default: "go.mod"
      skipBtrfs:
        type: string
        default: "true"

jobs:
  _:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Btrfs
      if: inputs.skipBtrfs == 'false'
      run: sudo apt-get install -y libbtrfs-dev

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.path-to-go-mod }}

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install golangci-lint
      run: task -p deps:install:golangci-lint

    - name: Lint
      run: task -p lint