name: tag:auto-create

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

env:
  GH_TOKEN: ${{ secrets.TOKEN }} 

jobs:
  release:
    name: Create release tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Relabel closed release PR
        run: |
          PR_NUMBER=$(gh pr list --state closed --label "autorelease: pending" --limit 1 --json number -q '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr edit $PR_NUMBER --remove-label "autorelease: pending"
            gh pr edit $PR_NUMBER --add-label "autorelease: tagged"
          fi

      - name: Get version from CHANGELOG.md
        id: get_version
        run: |
          VERSION=$(grep -m1 '^#\+ \[[0-9]\+\.[0-9]\+\.[0-9]\+\]' CHANGELOG.md | sed -E 's/^#+ \[([0-9]+\.[0-9]+\.[0-9]+)\].*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag via GitHub API
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"

          if gh api repos/${{ github.repository }}/git/ref/tags/$TAG &>/dev/null; then
            echo "Tag $TAG already exists. Skipping..."
            exit 0
          fi

          COMMIT_SHA=$(git rev-parse HEAD)

          gh api repos/${{ github.repository }}/git/refs \
            -f ref="refs/tags/$TAG" \
            -f sha="$COMMIT_SHA"